name: Deploy Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Supabase
        uses: supabase/supabase-cli-action@v1
        with:
          supabaseUrl: ${{ secrets.SUPABASE_URL }}
          supabaseKey: ${{ secrets.SUPABASE_KEY }}

      - name: Run Terraform
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Upload Terraform state to Supabase
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform.tfstate

      - name: Invoke Supabase function
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"bucket": "entrada_terraform", "key": "terraform/state/terraform.tfstate", "file": "terraform.tfstate"}' \
            "https://${{ secrets.SUPABASE_URL }}/storage/v1/object/upload"