name: Supabase Migrations Workflow

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Configure Supabase credentials
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Apply database migrations
        run: supabase db:push

      - name: Run tests (optional)
        run: npm test 
