name: SupbaseCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Function
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install project dependencies
      run: npm install
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest supabase 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F
    - name: Run tests
      run: pytest 
    - name: Install supabase-cli
      run: npm install -g supabase
    - name: Deploy Supabase Function
      run: |
        set -e
        supabase functions deploy --project-ref $PROJECT_ID
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    - name: Verify Function Deployment
      run: |
        supabase functions list --project-ref $PROJECT_ID
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    - name: Report Success
      run: echo "Sucesso! Acesso à Supabase realizado com sucesso."